# Use the official Prometheus image from Docker Hub
FROM prom/prometheus:v2.30.3

# Copy the Prometheus configuration file to the container
COPY prometheus.yml /etc/prometheus/prometheus.yml

# Expose the Prometheus web UI port
EXPOSE 9090
